2023-06-19 12:06:44,125 INFO    StreamThr :15356 [internal.py:wandb_internal():86] W&B internal server running at pid: 15356, started at: 2023-06-19 12:06:44.124757
2023-06-19 12:06:44,127 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status
2023-06-19 12:06:44,134 INFO    WriterThread:15356 [datastore.py:open_for_write():85] open: ./wandb/run-20230619_120644-uvt4x3qc/run-uvt4x3qc.wandb
2023-06-19 12:06:44,134 DEBUG   SenderThread:15356 [sender.py:send():369] send: header
2023-06-19 12:06:44,159 DEBUG   SenderThread:15356 [sender.py:send():369] send: run
2023-06-19 12:06:44,162 INFO    SenderThread:15356 [sender.py:_maybe_setup_resume():737] checking resume status for nlp/hw2/uvt4x3qc
2023-06-19 12:06:44,698 ERROR   SenderThread:15356 [internal_api.py:execute():323] 403 response executing GraphQL.
2023-06-19 12:06:44,698 ERROR   SenderThread:15356 [internal_api.py:execute():324] {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2023-06-19 12:06:44,699 ERROR   SenderThread:15356 [sender.py:send_run():955] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "/home/andrea/miniconda3/envs/nlp2023-hw2/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/andrea/miniconda3/envs/nlp2023-hw2/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 320, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/andrea/miniconda3/envs/nlp2023-hw2/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/andrea/miniconda3/envs/nlp2023-hw2/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/andrea/miniconda3/envs/nlp2023-hw2/lib/python3.9/site-packages/wandb/sdk/lib/gql_request.py", line 56, in execute
    request.raise_for_status()
  File "/home/andrea/miniconda3/envs/nlp2023-hw2/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andrea/miniconda3/envs/nlp2023-hw2/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 953, in send_run
    self._init_run(run, config_value_dict)
  File "/home/andrea/miniconda3/envs/nlp2023-hw2/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 991, in _init_run
    server_run, inserted, server_messages = self._api.upsert_run(
  File "/home/andrea/miniconda3/envs/nlp2023-hw2/lib/python3.9/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/andrea/miniconda3/envs/nlp2023-hw2/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/andrea/miniconda3/envs/nlp2023-hw2/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 1727, in upsert_run
    response = self.gql(
  File "/home/andrea/miniconda3/envs/nlp2023-hw2/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 292, in gql
    ret = self._retry_gql(
  File "/home/andrea/miniconda3/envs/nlp2023-hw2/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/home/andrea/miniconda3/envs/nlp2023-hw2/lib/python3.9/site-packages/wandb/util.py", line 908, in check_retry_fn
    return fallback_retry_fn(e)
  File "/home/andrea/miniconda3/envs/nlp2023-hw2/lib/python3.9/site-packages/wandb/util.py", line 850, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2023-06-19 12:06:49,702 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:06:54,703 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:06:59,704 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:07:04,705 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:07:09,706 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:07:14,707 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:07:19,708 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:07:24,710 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:07:29,711 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:07:34,712 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:07:39,714 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:07:44,715 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:07:49,716 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:07:54,717 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:07:59,719 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:08:04,720 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:08:09,722 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:08:14,723 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:08:19,723 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:08:24,724 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:08:29,725 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:08:34,725 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:08:39,726 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:08:44,726 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:08:49,727 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:08:54,727 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:08:59,728 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:09:04,729 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:09:09,730 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:09:14,731 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:09:19,732 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:09:24,733 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:09:29,734 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:09:34,735 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:09:39,736 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:09:44,737 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:09:49,738 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:09:54,739 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:09:59,740 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:10:04,742 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:10:09,742 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:10:14,743 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:10:19,744 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:10:24,745 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
2023-06-19 12:10:29,747 DEBUG   HandlerThread:15356 [handler.py:handle_request():144] handle_request: status_report
